apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  labels:
    mensageria: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      mensageria: rabbit
  template:
    metadata:
      labels:
        mensageria: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:latest
          ports:
            - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  selector:
    mensageria: rabbit
  ports:
    - name: rabbit
      protocol: TCP
      port: 5672
      targetPort: 5672
